name: Dynamic job tree test
on:
  push:
    branches: [main]
jobs:
  do-the-thing:
    name: Runs the job tree
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Generates a random job tree
        run: |
          python3 generate-job-tree.py > .github/workflows/generated.yaml
      - name: Commit workflow
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/generated.yaml
          git switch --create ci
          git commit --message "Add generated workflow"
          git push --force --set-upstream origin ci
